# SPDX-FileCopyrightText: 2023 Frederik Zorn <fz@zorrn.net>
#
# SPDX-License-Identifier: Apache-2.0

# Enable checking of Commits
enabled: true

# Check Pull Request and Commit title
titleAndCommits: true
# Every Commit must fit
anyCommit: true

# Allow revert commits
allowRevertCommits: true
