name: 'Build and push anki-sync container'

# run workflow on every branch, only upload on main (allow manual trigger)
on: [push, pull_request, workflow_dispatch]

jobs:
  build-push:
    # only push branch main to registry
    name: 'Build and push image'
    
    # use ubuntu as runner
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:

    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: redhat-actions/podman-login@v1
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      with:
        registry: ghcr.io
        username: federdaemn
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to DockerHub
      uses: redhat-actions/podman-login@v1
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      with:
        registry: docker.io
        username: federdaemn
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build image
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        containerfiles: |
          ./containerfile
        tags: |
          ghcr.io/federdaemn/oci-anki-sync:latest
          ghcr.io/federdaemn/oci-anki-sync:${{ github.sha }}
          docker.io/federdaemn/oci-anki-sync:latest
          docker.io/federdaemn/oci-anki-sync:${{ github.sha }}

    - name: Push image
      uses: redhat-actions/push-to-registry@v2
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      with:
        tags: ${{ steps.build_image.outputs.tags }}
